countries_state_dict = {"australia":  
    [['', 'All'], [ "act",  "ACT"], 
    [ "new-south-wales",  "New South Wales"], 
    [ "northern-territory",  "Northern Territory"], 
    [ "queensland",  "Queensland"], 
    [ "south-australia",  "South Australia"], 
    [ "tasmania",  "Tasmania"], 
    [ "victoria",  "Victoria"], 
    [ "western-australia",  "Western Australia"]],
    "austria":  [['', 'All'], [ "burgenland",  "Burgenland"], 
    [ "carinthia",  "Carinthia"], 
    [ "lower-austria",  "Lower Austria"], 
    [ "salzburg",  "Salzburg"], 
    [ "styria",  "Styria"], 
    [ "tyrol",  "Tyrol"], 
    [ "upper-austria",  "Upper Austria"], 
    [ "vienna",  "Vienna"], 
    [ "vorarlberg",  "Vorarlberg"]], "belgium":  [['', 'All'], [ "antwerpen",  "Antwerpen"], 
    [ "brabant-wallon",  "Brabant wallon"], 
    [ "hainaut",  "Hainaut"], 
    [ "limburg",  "Limburg"], 
    [ "liege",  "Liege"], 
    [ "luxembourg-belgium",  "Luxemburg"], 
    [ "namur",  "Namur"], 
    [ "oost-vlaanderen",  "Oost-Vlaanderen"], 
    [ "vlaams-brabant",  "Vlaams-Brabant"], 
    [ "west-vlaanderen",  "West-Vlaanderen"]], "bolivia":  [['', 'All'], [ "chuquisaca",  "Chuquisaca"], 
    [ "cochabamba",  "Cochabamba"], 
    [ "el-beni",  "El Beni"], 
    [ "la-paz",  "La Paz"], 
    [ "oruro",  "Oruro"], 
    [ "pando",  "Pando"], 
    [ "potosi",  "Potosi"], 
    [ "santa-cruz",  "Santa Cruz"], 
    [ "tarija",  "Tarija"]], "bonaire-st-eustatius-saba":  [['', 'All'], [ "bonaire",  "Bonaire"], 
    [ "saba",  "Saba"], 
    [ "sint-eustatius",  "Sint Eustatius"], 
    [ "federation-of-bosnia-and-herzegovina",  "Federation of B&H"], 
    [ "srpska",  "Srpska"]], "brazil":  [['', 'All'], [ "rio-grande-do-sul",  "Rio Grande do Sul"], 
    [ "rio-de-janeiro",  "Rio de Janeiro"], 
    [ "sao-paulo",  "Sao Paulo"]], "canada":  [['', 'All'], [ "alberta",  "Alberta"], 
    [ "british-columbia",  "British Columbia"], 
    [ "new-brunswick",  "New Brunswick"], 
    [ "newfoundland-and-labrador",  "Newfoundland and Labrador"], 
    [ "northwest-territories",  "Northwest Territories"], 
    [ "nova-scotia",  "Nova Scotia"], 
    [ "nunavut",  "Nunavut"], 
    [ "ontario",  "Ontario"], 
    [ "prince-edward-island",  "Prince Edward Island"], 
    [ "quebec",  "Quebec"], 
    [ "saskatchewan",  "Saskatchewan"], 
    [ "yukon",  "Yukon"]], "china":  [['', 'All'], [ "chongqing",  "Chongqing"], 
    [ "guangdong",  "Guangdong"], 
    [ "guangxi",  "Guangxi"], 
    [ "hebei",  "Hebei"], 
    [ "henan",  "Henan"], 
    [ "hubei",  "Hubei"], 
    [ "jiangsu",  "Jiangsu"], 
    [ "shandong",  "Shandong"], 
    [ "shanghai",  "Shanghai"], 
    [ "yunnan",  "Yunnan"], 
    [ "zhejiang",  "Zhejiang"]], "germany":  [['', 'All'], [ "baden-wurttemberg",  "Baden-Wurttemberg"], 
    [ "bavaria",  "Bavaria"], 
    [ "berlin",  "Berlin"], 
    [ "brandenburg",  "Brandenburg"], 
    [ "bremen",  "Bremen"], 
    [ "hamburg",  "Hamburg"], 
    [ "hesse",  "Hesse"], 
    [ "lower-saxony",  "Lower Saxony"], 
    [ "mecklenburg-vorpommern",  "Mecklenburg-Vorpommern"], 
    [ "north-rhine-westphalia",  "North Rhine-Westphalia"], 
    [ "rhineland-palatinate",  "Rhineland-Palatinate"], 
    [ "saarland",  "Saarland"], 
    [ "saxony",  "Saxony"], 
    [ "saxony-anhalt",  "Saxony-Anhalt"], 
    [ "schleswig-holstein",  "Schleswig-Holstein"], 
    [ "thuringia",  "Thuringia"]], "india":  [['', 'All'], [ "andhra-pradesh",  "Andhra Pradesh"], 
    [ "arunachal-pradesh",  "Arunachal Pradesh"], 
    [ "assam",  "Assam"], 
    [ "bihar",  "Bihar"], 
    [ "chandigarh",  "Chandigarh"], 
    [ "chhattisgarh",  "Chhattisgarh"], 
    [ "delhi",  "Delhi"], 
    [ "goa",  "Goa"], 
    [ "gujarat",  "Gujarat"], 
    [ "haryana",  "Haryana"], 
    [ "himachal-pradesh",  "Himachal Pradesh"], 
    [ "jammu-and-kashmir",  "Jammu and Kashmir"], 
    [ "jharkhand",  "Jharkhand"], 
    [ "karnataka",  "Karnataka"], 
    [ "kerala",  "Kerala"], 
    [ "madhya-pradesh",  "Madhya Pradesh"], 
    [ "maharashtra",  "Maharashtra"], 
    [ "manipur",  "Manipur"], 
    [ "meghalaya",  "Meghalaya"], 
    [ "mizoram",  "Mizoram"], 
    [ "nagaland",  "Nagaland"], 
    [ "odisha",  "Odisha"], 
    [ "puducherry",  "Puducherry"], 
    [ "punjab",  "Punjab"], 
    [ "rajasthan",  "Rajasthan"], 
    [ "sikkim",  "Sikkim"], 
    [ "tamil-nadu",  "Tamil Nadu"], 
    [ "telangana",  "Telangana"], 
    [ "tripura",  "Tripura"], 
    [ "uttar-pradesh",  "Uttar Pradesh"], 
    [ "uttarakhand",  "Uttarakhand"], 
    [ "west-bengal",  "West Bengal"]], "iraq":  [['', 'All'], [ "iraq-regional",  "Except Kurdistan"], 
    [ "iraq-kurdistan",  "Kurdistan"]], "italy":  [['', 'All'], [ "bari",  "Bari"], 
    [ "bologna",  "Bologna"], 
    [ "florence",  "Florence"], 
    [ "genoa",  "Genoa"], 
    [ "milan",  "Milan"], 
    [ "naples",  "Naples"], 
    [ "sicily",  "Palermo"], 
    [ "rome",  "Rome"], 
    [ "sardinia",  "Sardinia"], 
    [ "trieste",  "Trieste"], 
    [ "turin",  "Turin"], 
    [ "venice",  "Venice"]], "malaysia":  [['', 'All'], [ "johor",  "Johor"], 
    [ "kedah",  "Kedah"], 
    [ "kelantan",  "Kelantan"], 
    [ "kuala-lumpur",  "Kuala Lumpur"], 
    [ "labuan",  "Labuan"], 
    [ "melaka",  "Melaka"], 
    [ "negeri-sembilan",  "Negeri Sembilan"], 
    [ "pahang",  "Pahang"], 
    [ "penang",  "Penang"], 
    [ "perak",  "Perak"], 
    [ "perlis",  "Perlis"], 
    [ "putrajaya",  "Putrajaya"], 
    [ "sabah",  "Sabah"], 
    [ "sarawak",  "Sarawak"], 
    [ "selangor",  "Selangor"], 
    [ "terengganu",  "Terengganu"]], "moldova":  [['', 'All'], [ "moldova-cahul",  "Cahul"], 
    [ "moldova-chisinau",  "Chisinau"]], "nepal":  [['', 'All'], [ "gandaki-pradesh",  "Gandaki Pradesh"], 
    [ "karnali",  "Karnali"], 
    [ "kathmandu-valley",  "Kathmandu Valley"], 
    [ "province-1",  "Koshi"], 
    [ "province-2",  "Madhesh Pradesh"], 
    [ "sudurpashchim-pradesh",  "Sudurpashchim Pradesh"]], "new-zealand":  [['', 'All'], [ "auckland",  "Auckland"], 
    [ "bay-of-plenty",  "Bay of Plenty"], 
    [ "canterbury",  "Canterbury"], 
    [ "chatham-islands",  "Chatham Islands Territory"], 
    [ "gisborne",  "Gisborne"], 
    [ "gisborne",  "Hawke's Bay"], 
    [ "manawatu-wanganui",  "Manawatu-Wanganui"], 
    [ "marlborough",  "Marlborough"], 
    [ "nelson",  "Nelson"], 
    [ "northland",  "Northland"], 
    [ "otago",  "Otago"], 
    [ "southland",  "Southland"], 
    [ "taranaki",  "Taranaki"], 
    [ "tasman",  "Tasman"], 
    [ "waikato",  "Waikato"], 
    [ "wellington",  "Wellington"], 
    [ "west-coast",  "West Coast"], 
    [ "west-coast",  "West Coast"]], "nigeria":  [['', 'All'], [ "abia",  "Abia"], 
    [ "adamawa",  "Adamawa"], 
    [ "akwa-ibom",  "Akwa Ibom"], 
    [ "anambra",  "Anambra"], 
    [ "bauchi",  "Bauchi"], 
    [ "bayelsa",  "Bayelsa"], 
    [ "borno",  "Borno"], 
    [ "cross-river",  "Cross River"], 
    [ "delta",  "Delta"], 
    [ "ebonyi",  "Ebonyi"], 
    [ "edo",  "Edo"], 
    [ "ekiti",  "Ekiti"], 
    [ "enugu",  "Enugu"], 
    [ "imo",  "Imo"], 
    [ "jigawa",  "Jigawa"], 
    [ "kaduna",  "Kaduna"], 
    [ "kano",  "Kano"], 
    [ "katsina",  "Katsina"], 
    [ "kebbi",  "Kebbi"], 
    [ "kogi",  "Kogi"], 
    [ "kwara",  "Kwara"], 
    [ "lagos",  "Lagos"], 
    [ "niger-ng",  "Niger State"], 
    [ "nigeria-regional",  "Nigeria Other"], 
    [ "ogun",  "Ogun"], 
    [ "ondo",  "Ondo"], 
    [ "osun",  "Osun"], 
    [ "oyo",  "Oyo"], 
    [ "plateau",  "Plateau"], 
    [ "rivers",  "Rivers"], 
    [ "sokoto",  "Sokoto"], 
    [ "yobe",  "Yobe"], 
    [ "zamfara",  "Zamfara"]], "pakistan":  [['', 'All'], [ "azad-kashmir",  "Azad Kashmir"], 
    [ "balochistan",  "Balochistan"], 
    [ "islamabad",  "Islamabad Capital Territory"], 
    [ "khyber-pakhtunkhwa",  "Khyber Pakhtunkhwa"], 
    [ "pakistan-punjab",  "Punjabi"], 
    [ "sindh",  "Sindh"]], "philippines":  [['', 'All'], [ "batangas",  "Batangas"], 
    [ "bukidnon",  "Bukidnon"], 
    [ "bulacan",  "Bulacan"], 
    [ "cebu",  "Cebu"], 
    [ "davao",  "Davao"], 
    [ "manila-ncr",  "Manila (NCR)"], 
    [ "quezon",  "Quezon"], 
    [ "rizal",  "Rizal"], 
    [ "Sulu",  "Sulu"]], "portugal":  [['', 'All'], [ "azores",  "Azores"], 
    [ "lisbon",  "Lisbon"], 
    [ "madeira",  "Madeira"], 
    [ "porto",  "Porto"]], "spain":  [['', 'All'], [ "andalucia",  "Andalucia"], 
    [ "aragon",  "Aragon"], 
    [ "asturias",  "Asturias"], 
    [ "balearic-islands",  "Balearic Islands"], 
    [ "basque-country",  "Basque Country"], 
    [ "canary-islands",  "Canary Islands"], 
    [ "cantabria",  "Cantabria"], 
    [ "castile-and-leon",  "Castile and Leon"], 
    [ "castilla-la-mancha",  "Castilla-La Mancha"], 
    [ "catalonia",  "Catalonia"], 
    [ "ceuta",  "Ceuta"], 
    [ "extremadura",  "Extremadura"], 
    [ "galicia",  "Galicia"], 
    [ "la-rioja",  "La Rioja"], 
    [ "madrid",  "Madrid"], 
    [ "melilla",  "Melilla"], 
    [ "murcia",  "Murcia"], 
    [ "navarra",  "Navarra"], 
    [ "valenciana",  "Valenciana"]], "switzerland":  [['', 'All'], [ "aargau",  "Aargau"], 
    [ "appenzell-ausserrhoden",  "Appenzell Ausserrhoden"], 
    [ "appenzell-innerrhoden",  "Appenzell Innerrhoden"], 
    [ "basel-landschaft",  "Basel-Landschaft"], 
    [ "basel-stadt",  "Basel-Stadt"], 
    [ "bern",  "Bern"], 
    [ "fribourg",  "Fribourg"], 
    [ "geneva",  "Geneva"], 
    [ "glarus",  "Glarus"], 
    [ "graubunden",  "Graubunden"], 
    [ "jura",  "Jura"], 
    [ "lucerne",  "Lucerne"], 
    [ "neuchatel",  "Neuchatel"], 
    [ "nidwalden",  "Nidwalden"], 
    [ "obwalden",  "Obwalden"], 
    [ "schaffhausen",  "Schaffhausen"], 
    [ "schwyz",  "Schwyz"], 
    [ "solothurn",  "Solothurn"], 
    [ "st-gallen",  "St. Gallen"], 
    [ "thurgau",  "Thurgau"], 
    [ "ticino",  "Ticino"], 
    [ "uri",  "Uri"], 
    [ "valais",  "Valais"], 
    [ "vaud",  "Vaud"], 
    [ "zug",  "Zug"], 
    [ "zurich",  "Zurich"]], "united-kingdom":  [['', 'All'], [ "england",  "England"], 
    [ "northern-ireland",  "Northern Ireland"], 
    [ "scotland",  "Scotland"], 
    [ "wales",  "Wales"]], "usa":  [['', 'All'], [ "alabama",  "Alabama"], 
    [ "alaska",  "Alaska"], 
    [ "arizona",  "Arizona"], 
    [ "arkansas",  "Arkansas"], 
    [ "california",  "California"], 
    [ "colorado",  "Colorado"], 
    [ "connecticut",  "Connecticut"], 
    [ "delaware",  "Delaware"], 
    [ "dc",  "District of Columbia"], 
    [ "florida",  "Florida"], 
    [ "georgia-usa",  "Georgia"], 
    [ "hawaii",  "Hawaii"], 
    [ "idaho",  "Idaho"], 
    [ "illinois",  "Illinois"], 
    [ "indiana",  "Indiana"], 
    [ "iowa",  "Iowa"], 
    [ "kansas",  "Kansas"], 
    [ "kentucky",  "Kentucky"], 
    [ "louisiana",  "Louisiana"], 
    [ "maine",  "Maine"], 
    [ "maryland",  "Maryland"], 
    [ "massachusetts",  "Massachusetts"], 
    [ "michigan",  "Michigan"], 
    [ "minnesota",  "Minnesota"], 
    [ "mississippi",  "Mississippi"], 
    [ "missouri",  "Missouri"], 
    [ "montana",  "Montana"], 
    [ "nebraska",  "Nebraska"], 
    [ "nevada",  "Nevada"], 
    [ "new-hampshire",  "New Hampshire"], 
    [ "new-jersey",  "New Jersey"], 
    [ "new-mexico",  "New Mexico"], 
    [ "new-york",  "New York"], 
    [ "north-carolina",  "North Carolina"], 
    [ "north-dakota",  "North Dakota"], 
    [ "ohio",  "Ohio"], 
    [ "oklahoma",  "Oklahoma"], 
    [ "oregon",  "Oregon"], 
    [ "pennsylvania",  "Pennsylvania"], 
    [ "rhode-island",  "Rhode Island"], 
    [ "south-carolina",  "South Carolina"], 
    [ "south-dakota",  "South Dakota"], 
    [ "tennessee",  "Tennessee"], 
    [ "texas",  "Texas"], 
    [ "utah",  "Utah"], 
    [ "vermont",  "Vermont"], 
    [ "virginia",  "Virginia"], 
    [ "washington",  "Washington"], 
    [ "west-virginia",  "West Virginia"], 
    [ "wisconsin",  "Wisconsin"], 
    [ "wyoming",  "Wyoming"]]}
